export const CABINET_CONFIG = {
  name: "La Maison Dentaire",
  slogan: "Votre centre de soins dentaires à Strasbourg",
  subtitle: "Notre équipe vous accueille dans un environnement moderne et rassurant pour une prise en charge complète de votre santé bucco-dentaire. Située face à l’arrêt de tram Elsau, La Maison Dentaire reçoit adultes et enfants avec une approche humaine et accessible.",
  address: "21 Rue Léonard de Vinci",
  logo: "/logo1.webp",
  city: "Strasbourg",
  zip: "67200",
  phone: "03 88 67 72 57",
  email: "info@la-maison-dentaire.fr",
  formspreeEndpoint: "https://formspree.io/f/mnjoezrd",
  openingHours: [
    { day: "Lundi", hours: "9h - 19h" },
    { day: "Mardi", hours: "9h - 19h" },
    { day: "Mercredi", hours: "9h - 19h" },
    { day: "Jeudi", hours: "9h - 19h" },
    { day: "Vendredi", hours: "9h - 18h" },
    { day: "Samedi", hours: "Fermé" },
    { day: "Dimanche", hours: "Fermé" },
  ],
  googleMapsEmbedUrl: "https://www.google.com/maps?q=21+Rue+L%C3%A9onard+de+Vinci,+67200+Strasbourg,+France&output=embed",
  placeId: "VOTRE_PLACE_ID",
  googlePlacesApiKey: "VOTRE_GOOGLE_PLACES_API_KEY",
  doctolibProfileUrl: "https://www.doctolib.fr/centre-medical-et-dentaire/strasbourg/maison-dentaire-strasbourg",
  socialLinks: {
    facebook: "https://facebook.com",
    instagram: "https://instagram.com",
    linkedin: "https://linkedin.com",
  },
  contactEmail: "info@la-maison-dentaire.fr",
  webhookUrl: "",
};

export const TEAM_MEMBERS = [
  {
    id: "dr-gumustepe",
    name: "Dr. Hakan GUMUSTEPE",
    title: "Chirurgien-Dentiste",
    specialty: "Implantologie & Esthétique",
    bio: "Diplômé de la Faculté de Chirurgie-Dentaire de Strasbourg.",
    diplomas: ["Doctorat en Chirurgie Dentaire – Université Paris Descartes", "DU Implantologie – Université Paris Diderot", "Formation continue en esthétique dentaire"],
    approach: "Une approche douce et rassurante, avec un accent sur la communication et l'explication de chaque étape du traitement.",
    image: "male",
  },
  {
    id: "dr-joseph",
    name: "Dr. Constance JOSEPH",
    title: "Chirurgien-Dentiste",
    specialty: "Parodontologie & Soins conservateurs",
    bio: "Diplômée de la Faculté de Chirurgie-Dentaire de Strasbourg.",
    diplomas: ["Doctorat en Chirurgie Dentaire – Université de Strasbourg", "CES Parodontologie", "Certification en dentisterie numérique"],
    approach: "Un praticien à l'écoute, privilégiant les techniques mini-invasives et la prévention pour préserver au maximum les dents naturelles.",
    image: "female",
  },
    {
    id: "dr-elassad",
    name: "Dr. Ghita ELASSAD",
    title: "Chirurgien-Dentiste",
    specialty: "Parodontologie & Soins conservateurs",
    bio: "Diplômé de la Faculté de Chirurgie-Dentaire de Strasbourg.",
    diplomas: ["Doctorat en Chirurgie Dentaire – Université de Strasbourg", "CES Parodontologie", "Certification en dentisterie numérique"],
    approach: "Un praticien à l'écoute, privilégiant les techniques mini-invasives et la prévention pour préserver au maximum les dents naturelles.",
    image: "male",
  },
    {
    id: "dr-ucar",
    name: "Dr. Fatih UCAR",
    title: "Chirurgien-Dentiste",
    specialty: "Parodontologie & Soins conservateurs",
    bio: "Diplômé de la Faculté de Chirurgie-Dentaire de Strasbourg.",
    diplomas: ["Doctorat en Chirurgie Dentaire – Université de Strasbourg", "CES Parodontologie", "Certification en dentisterie numérique"],
    approach: "Un praticien à l'écoute, privilégiant les techniques mini-invasives et la prévention pour préserver au maximum les dents naturelles.",
    image: "male",
  },
    {
    id: "dr-stemmer",
    name: "Dr. Pauline STEMMER",
    title: "Chirurgien-Dentiste",
    specialty: "Parodontologie & Soins conservateurs",
    bio: "Diplômée de la Faculté de Chirurgie-Dentaire de Strasbourg.",
    diplomas: ["Doctorat en Chirurgie Dentaire – Université de Strasbourg", "CES Parodontologie", "Certification en dentisterie numérique"],
    approach: "Un praticien à l'écoute, privilégiant les techniques mini-invasives et la prévention pour préserver au maximum les dents naturelles.",
    image: "female",
  },
    {
    id: "dr-wilczynska",
    name: "Dr. Bozena WILCZYNSKA",
    title: "Chirurgien-Dentiste",
    specialty: "Parodontologie & Soins conservateurs",
    bio: "Diplômée de la Faculté de Chirurgie-Dentaire de Cracovie.",
    diplomas: ["Doctorat en Chirurgie Dentaire – Université de Strasbourg", "CES Parodontologie", "Certification en dentisterie numérique"],
    approach: "Un praticien à l'écoute, privilégiant les techniques mini-invasives et la prévention pour préserver au maximum les dents naturelles.",
    image: "female",
  },
    {
    id: "dr-galfi",
    name: "Dr. Eliot GALFI",
    title: "Chirurgien-Dentiste",
    specialty: "Parodontologie & Soins conservateurs",
    bio: "Diplômé de la Faculté de Chirurgie-Dentaire de Strasbourg.",
    diplomas: ["Doctorat en Chirurgie Dentaire – Université de Strasbourg", "CES Parodontologie", "Certification en dentisterie numérique"],
    approach: "Un praticien à l'écoute, privilégiant les techniques mini-invasives et la prévention pour préserver au maximum les dents naturelles.",
    image: "male",
  },
];

export const SOINS = [
  {
    id: "parodontologie",
    title: "Parodontologie",
    icon: "ShieldCheck",
    shortDesc: "Prévention et traitement des maladies gencives.",
    description: "La parodontologie traite les gencives et les tissus de soutien de la dent. Elle permet de prévenir, diagnostiquer et soigner les inflammations gingivales et les maladies parodontales.",
    whenToConsult: "En cas de saignement des gencives, de mauvaise haleine persistante, de sensibilité ou de déchaussement.",
    procedure: "Après un bilan complet, le praticien réalise un nettoyage ciblé et met en place un suivi adapté à votre situation.",
    duration: "30 à 45 minutes",
    comfort: "Généralement confortable, avec une prise en charge douce et progressive",
    afterCare: "Maintenir une hygiène rigoureuse et respecter les contrôles de suivi recommandés.",
  },
  {
    id: "caries",
    title: "Soins conservateurs",
    icon: "Shield",
    shortDesc: "préserver et restaurer vos dents naturelles.",
    description: "Les soins conservateurs visent à traiter les lésions dentaires de manière précise tout en gardant un maximum de tissu sain. Ils incluent notamment le traitement des caries.",
    whenToConsult: "Douleur au chaud ou au froid, sensibilité, tache sombre sur une dent ou fracture localisée.",
    procedure: "Après anesthésie locale, la partie cariée est retirée et remplacée par un composite de la couleur de votre dent.",
    duration: "30 minutes à 1 heure",
    comfort: "Traitement sous anesthésie locale, totalement indolore",
    afterCare: "Éviter de manger du côté traité pendant 2h. Reprendre le brossage normalement.",
  },
  {
    id: "couronnes",
    title: "Prothèses",
    icon: "Crown",
    shortDesc: "Remplacement et restauration des dents absentes ou fragilisées.",
    description: "Les prothèses dentaires permettent de restaurer l'esthétique et la fonction des dents grâce à des solutions fixes ou amovibles adaptées à chaque patient.",
    whenToConsult: "Dent très abîmée, fracturée, dévitalisée, ou besoin de remplacer une ou plusieurs dents manquantes.",
    procedure: "Après un bilan précis, une empreinte est prise puis la prothèse est conçue sur mesure avant sa pose.",
    duration: "2 séances de 45 minutes",
    comfort: "Anesthésie locale si nécessaire, avec une pose progressive et maîtrisée",
    afterCare: "Entretenir la prothèse selon les conseils du praticien et maintenir un brossage régulier.",
  },
  {
    id: "implants",
    title: "Implants dentaires",
    icon: "Wrench",
    shortDesc: "Une solution durable pour remplacer les dents manquantes.",
    description: "L'implant dentaire est une racine artificielle en titane posée dans l'os de la mâchoire. Il sert de support à une couronne, un bridge ou une prothèse. C'est la solution la plus fiable et durable.",
    whenToConsult: "Dent manquante, prothèse amovible inconfortable, souhait d'une solution fixe.",
    procedure: "Pose chirurgicale de l'implant, période de cicatrisation (2-4 mois), puis pose de la couronne définitive.",
    duration: "Chirurgie : 1h | Traitement complet : 3-6 mois",
    comfort: "Intervention sous anesthésie locale, douleurs post-opératoires très modérées",
    afterCare: "Alimentation molle pendant 1 semaine. Hygiène rigoureuse. Suivi régulier.",
  },
  {
    id: "radiologie-dentaire",
    title: "Radiologie dentaire",
    icon: "Radio",
    shortDesc: "Imagerie numérique pour un diagnostic précis.",
    description: "La radiologie dentaire nous aide à visualiser les zones non accessibles à l'examen clinique pour établir un diagnostic fiable et planifier les soins.",
    whenToConsult: "Lors d'un bilan complet, avant certains soins ou en cas de douleur sans cause visible.",
    procedure: "Réalisation d'images ciblées avec un équipement numérique pour analyser précisément la situation.",
    duration: "Quelques minutes",
    comfort: "Examen rapide, non invasif et généralement très confortable",
    afterCare: "Aucune précaution particulière dans la majorité des cas.",
  },
  {
    id: "chirurgie",
    title: "Chirurgie",
    icon: "Stethoscope",
    shortDesc: "Des soins chirurgicaux réaalisés avec précision et sécurité.",
    description: "La chirurgie dentaire regroupe les interventions nécessaires pour traiter certaines situations complexes, dans un cadre maîtrisé et rassurant.",
    whenToConsult: "Pour une extraction, une intervention préparatoire à un implant ou un soin nécessitant un geste chirurgical.",
    procedure: "Le praticien vous explique chaque étape, réalise l'intervention sous anesthésie locale, puis assure le suivi post-opératoire.",
    duration: "30 minutes à 1 heure",
    comfort: "Intervention sous anesthésie locale avec priorité au confort",
    afterCare: "Respecter les consignes post-opératoires et revenir en contrôle si nécessaire.",
  },
  {
    id: "urgences",
    title: "Urgences dentaires",
    icon: "AlertCircle",
    shortDesc: "Prise en charge rapide des douleurs et urgences dentaires.",
    description: "Les urgences dentaires nécessitent une évaluation rapide pour soulager la douleur, traiter la cause et éviter toute aggravation.",
    whenToConsult: "Douleur intense, gonflement, dent cassée, abcès ou traumatisme dentaire.",
    procedure: "Nous réalisons un diagnostic rapide, un soulagement immédiat si nécessaire, puis nous organisons le traitement adapté.",
    duration: "30 minutes à 1 heure",
    comfort: "Priorité au soulagement de la douleur et à une prise en charge rassurante",
    afterCare: "Suivre les consignes données au cabinet et prévoir un contrôle si recommandé.",
  },
  {
    id: "pedodontie",
    title: "Pédodontie",
    icon: "Baby",
    shortDesc: "Des soins adaptés et bienveillants pour les plus petits.",
    description: "La pédodontie est la spécialité dédiée aux soins dentaires des enfants. Notre approche ludique et rassurante permet aux enfants de vivre une expérience positive chez le dentiste.",
    whenToConsult: "Première visite recommandée dès 3 ans, puis suivi régulier tous les 6 mois.",
    procedure: "Examen adapté, apprentissage du brossage, soins préventifs (scellement de sillons) et curatifs si nécessaire.",
    duration: "20 à 30 minutes",
    comfort: "Approche ludique et douce, adaptée à l'âge de l'enfant",
    afterCare: "Encourager le brossage régulier et limiter les sucreries.",
  },
];

export const REVIEWS = [
  { author: "Marie L.", rating: 5, text: "Excellent cabinet ! L'équipe est très professionnelle et rassurante. Je recommande vivement.", date: "Il y a 2 semaines" },
  { author: "Pierre D.", rating: 5, text: "Dr Martin est exceptionnelle. Elle a pris le temps de tout m'expliquer et le résultat est parfait.", date: "Il y a 1 mois" },
  { author: "Isabelle R.", rating: 5, text: "Cabinet moderne et propre. L'accueil est chaleureux. Plus de peur d'aller chez le dentiste !", date: "Il y a 1 mois" },
  { author: "Jean-Marc T.", rating: 4, text: "Très bon suivi pour mes implants. Résultat naturel et durable. Merci à toute l'équipe.", date: "Il y a 2 mois" },
  { author: "Sophie B.", rating: 5, text: "Mon fils de 5 ans adore y aller ! L'approche avec les enfants est formidable.", date: "Il y a 2 mois" },
  { author: "Laurent M.", rating: 5, text: "Enfin un cabinet qui prend le temps. Les explications sont claires et les soins de qualité.", date: "Il y a 3 mois" },
  { author: "Claire V.", rating: 5, text: "Blanchiment réussi ! Résultat naturel, je suis ravie. Équipe au top.", date: "Il y a 3 mois" },
  { author: "François G.", rating: 4, text: "Bonne prise en charge d'urgence un samedi matin. Réactif et efficace.", date: "Il y a 4 mois" },
];

export const FAQ_ITEMS = [
  { q: "Est-ce que les soins dentaires font mal ?", a: "La grande majorité des soins sont réalisés sous anesthésie locale et sont totalement indolores. Notre priorité est votre confort. N'hésitez pas à nous signaler toute appréhension." },
  { q: "À quelle fréquence dois-je consulter ?", a: "Nous recommandons une visite de contrôle tous les 6 mois à 1 an. Un suivi régulier permet de détecter et traiter les problèmes à un stade précoce." },
  { q: "Acceptez-vous les urgences ?", a: "Oui, nous réservons des créneaux pour les urgences dentaires. Appelez-nous directement par téléphone pour une prise en charge rapide." },
  { q: "Êtes-vous conventionné ?", a: "Oui, notre cabinet est conventionné secteur 1. La plupart des soins courants sont pris en charge par l'Assurance Maladie et votre mutuelle." },
  { q: "Comment se déroule une première consultation ?", a: "La première consultation dure environ 45 minutes. Elle comprend un échange sur vos attentes, un examen clinique complet, des radiographies si nécessaire, et l'élaboration d'un plan de traitement personnalisé." },
  { q: "Proposez-vous le paiement en plusieurs fois ?", a: "Oui, nous proposons des facilités de paiement pour les traitements importants. N'hésitez pas à nous en parler lors de votre consultation." },
  { q: "Les implants dentaires sont-ils remboursés ?", a: "Les implants ne sont pas remboursés par l'Assurance Maladie, mais de nombreuses mutuelles proposent une prise en charge partielle. Nous vous fournirons un devis détaillé." },
  { q: "À partir de quel âge emmener mon enfant chez le dentiste ?", a: "Nous recommandons une première visite dès l'âge de 3 ans, ou dès l'apparition des premières dents de lait si vous avez des inquiétudes." },
  { q: "Quels moyens de paiement acceptez-vous ?", a: "Nous acceptons les cartes bancaires, les chèques, les espèces et la télétransmission avec votre carte Vitale." },
  { q: "Le centre est-il accessible aux personnes à mobilité réduite ?", a: "Oui, notre cabinet est entièrement accessible aux personnes à mobilité réduite (PMR). Un accès de plain-pied et des équipements adaptés sont à votre disposition." },
];

export const BLOG_ARTICLES = [
  {
    id: "bien-se-brosser-les-dents",
    title: "Comment bien se brosser les dents ?",
    excerpt: "Découvrez les techniques de brossage recommandées par nos dentistes pour une hygiène bucco-dentaire optimale.",
    content: `Le brossage des dents est le geste fondamental de l'hygiène bucco-dentaire. Pourtant, beaucoup de personnes ne le réalisent pas correctement.\n\n La technique recommandée\n\nUtilisez une brosse à dents souple et un dentifrice fluoré. Placez la brosse à 45° par rapport à la gencive et effectuez des mouvements circulaires doux, de la gencive vers la dent.\n\n Durée et fréquence\n\nBrossez-vous les dents pendant **2 minutes minimum**, au moins **2 fois par jour** (matin et soir). Le brossage du soir est le plus important.\n\n N'oubliez pas\n\n- Changez de brosse à dents tous les 3 mois\n- Utilisez du fil dentaire ou des brossettes interdentaires\n- Complétez avec un bain de bouche si recommandé par votre dentiste`,
    category: "Hygiène",
    readTime: "3 min",
  },
  {
    id: "frequence-consultation",
    title: "À quelle fréquence consulter son dentiste ?",
    excerpt: "Un suivi régulier est essentiel pour prévenir les problèmes dentaires. Voici nos recommandations.",
    content: "Un suivi dentaire régulier est la clé d'une bonne santé bucco-dentaire...",
    category: "Prévention",
    readTime: "4 min",
  },
  {
    id: "sensibilite-dentaire",
    title: "Sensibilité dentaire : causes et solutions",
    excerpt: "Douleur au chaud, au froid ? La sensibilité dentaire touche de nombreuses personnes. Découvrez comment y remédier.",
    content: "La sensibilité dentaire se manifeste par une douleur vive et brève...",
    category: "Soins",
    readTime: "5 min",
  },
  {
    id: "dents-de-sagesse",
    title: "Dents de sagesse : faut-il les extraire ?",
    excerpt: "Les dents de sagesse posent souvent problème. Découvrez quand et pourquoi il peut être nécessaire de les retirer.",
    content: "Les dents de sagesse apparaissent généralement entre 17 et 25 ans...",
    category: "Chirurgie",
    readTime: "4 min",
  },
  {
    id: "gingivite",
    title: "Gingivite : comment la reconnaître et la traiter ?",
    excerpt: "Gencives rouges, gonflées ou qui saignent ? Il s'agit peut-être d'une gingivite. Voici comment agir.",
    content: "La gingivite est une inflammation des gencives causée par l'accumulation de plaque dentaire...",
    category: "Parodontologie",
    readTime: "4 min",
  },
  {
    id: "blanchiment-dentaire",
    title: "Blanchiment dentaire : ce qu'il faut savoir",
    excerpt: "Envie d'un sourire plus blanc ? Découvrez les options de blanchiment sûres et efficaces.",
    content: "Le blanchiment dentaire est un traitement esthétique très demandé...",
    category: "Esthétique",
    readTime: "5 min",
  },
  {
    id: "implants-dentaires-guide",
    title: "Guide complet des implants dentaires",
    excerpt: "Tout ce que vous devez savoir sur les implants : procédure, durée, coût et résultats.",
    content: "L'implant dentaire est considéré comme la meilleure solution pour remplacer une dent manquante...",
    category: "Implantologie",
    readTime: "6 min",
  },
  {
    id: "soins-dentaires-enfants",
    title: "Soins dentaires pour les enfants : guide pour les parents",
    excerpt: "Comment prendre soin des dents de votre enfant dès le plus jeune âge.",
    content: "La santé bucco-dentaire de votre enfant se construit dès les premiers mois de vie...",
    category: "Pédodontie",
    readTime: "5 min",
  },
];

export const TECHNOLOGIES = [
  { title: "Radio numérique", description: "Imagerie numérique haute définition pour un diagnostic rapide et précis.", benefit: "Diagnostic précis" },
  { title: "Caméra intra-orale", description: "Visualisation en temps réel afin de mieux comprendre votre traitement.", benefit: "Communication simplifiée" },
  { title: "Empreinte optique 3D", description: "Scanner numérique permettant des empreintes rapides et confortables.", benefit: "Confort optimal" },
  { title: "Scanner 3D (CBCT)", description: "Imagerie 3D pour l’analyse et la planification des traitements complexes.", benefit: "Imagerie avancée" },
  { title: "Stérilisation haute performance", description: "Protocoles de stérilisation rigoureux conformes aux normes en vigueur.", benefit: "Sécurité sanitaire" },
  { title: "Équipements dernière génération", description: "Fauteuils ergonomiques, éclairage LED, et instruments de dernière technologie.", benefit: "Confort et performance" },
];
